/**
 * DESIGN PREVIEW DATA — COMPANIES & INTELLIGENCE
 * Isolated mock data for rendering customer-facing company directory, profiles, and comparison view.
 */
import { CompanyItem, CompanySignalSnapshot, CompanyJobSummary } from "@/types/companies";

export const MOCK_COMPANIES: CompanyItem[] = [
  {
    id: "comp-stripe",
    name: "Stripe",
    slug: "stripe",
    domain: "stripe.com",
    websiteUrl: "https://stripe.com",
    logoUrl: null,
    description: "Financial infrastructure platform for the internet.",
    industry: "Fintech & Payments",
    headquarters: "San Francisco, CA / Dublin, Ireland",
    employeeCount: 8000,
    isVerified: true,
  },
  {
    id: "comp-cloudflare",
    name: "Cloudflare",
    slug: "cloudflare",
    domain: "cloudflare.com",
    websiteUrl: "https://cloudflare.com",
    logoUrl: null,
    description: "Security, performance, and reliability for the global Internet.",
    industry: "Cloud Infrastructure & Cybersecurity",
    headquarters: "San Francisco, CA",
    employeeCount: 3500,
    isVerified: true,
  },
  {
    id: "comp-openai",
    name: "OpenAI",
    slug: "openai",
    domain: "openai.com",
    websiteUrl: "https://openai.com",
    logoUrl: null,
    description: "AI research and deployment company creating safe AGI.",
    industry: "Artificial Intelligence",
    headquarters: "San Francisco, CA",
    employeeCount: 1500,
    isVerified: true,
  },
  {
    id: "comp-vercel",
    name: "Vercel",
    slug: "vercel",
    domain: "vercel.com",
    websiteUrl: "https://vercel.com",
    logoUrl: null,
    description: "The platform for frontend developers and Next.js innovation.",
    industry: "Developer Tools & Cloud",
    headquarters: "Remote / San Francisco, CA",
    employeeCount: 600,
    isVerified: true,
  },
  {
    id: "comp-datadog",
    name: "Datadog",
    slug: "datadog",
    domain: "datadoghq.com",
    websiteUrl: "https://datadoghq.com",
    logoUrl: null,
    description: "Monitoring and observability platform for cloud applications.",
    industry: "Observability & Security",
    headquarters: "New York, NY",
    employeeCount: 5000,
    isVerified: true,
  },
  {
    id: "comp-github",
    name: "GitHub",
    slug: "github",
    domain: "github.com",
    websiteUrl: "https://github.com",
    logoUrl: null,
    description: "The complete developer platform to build, scale, and deliver secure software.",
    industry: "Developer Tools & Open Source",
    headquarters: "San Francisco, CA",
    employeeCount: 3000,
    isVerified: true,
  }
];

export const MOCK_COMPANY_JOBS: Record<string, CompanyJobSummary[]> = {
  stripe: [
    {
      id: "job-stripe-staff-plat",
      title: "Staff Platform Engineer — High-Throughput Settlement Infrastructure",
      location: "San Francisco, CA (Hybrid)",
      workMode: "hybrid",
      employmentType: "full_time",
      seniority: "Staff",
      salaryMin: 225000,
      salaryMax: 290000,
      salaryCurrency: "USD",
      salaryInterval: "yearly",
      sourcePostedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
      firstDiscoveredAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
    },
  ],
  cloudflare: [
    {
      id: "job-cloudflare-runtime",
      title: "Staff Systems Engineer — Cloudflare Workers Runtime Core",
      location: "Austin, TX (Hybrid)",
      workMode: "hybrid",
      employmentType: "full_time",
      seniority: "Staff",
      salaryMin: 210000,
      salaryMax: 270000,
      salaryCurrency: "USD",
      salaryInterval: "yearly",
      sourcePostedAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
      firstDiscoveredAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    },
  ],
};

export const MOCK_SNAPSHOTS: CompanySignalSnapshot[] = [
  {
    identity: {
      id: "comp-stripe",
      name: "Stripe",
      slug: "stripe",
      logoUrl: null,
      websiteUrl: "https://stripe.com",
    },
    profile: {
      domain: "stripe.com",
      industry: "Fintech & Payments",
      headquarters: "San Francisco, CA / Dublin, Ireland",
      employeeCount: 8000,
      description: "Stripe is a financial infrastructure platform for businesses. Millions of companies—from the world’s largest enterprises to the most ambitious startups—use Stripe to accept payments, grow their revenue, and accelerate new business opportunities.",
      techStack: ["Ruby", "Go", "Java", "PostgreSQL", "Kafka", "Sorbet", "React", "AWS"],
    },
    hiring: {
      activeJobCount: 342,
      newJobsLast30Days: 48,
      newJobsLast90Days: 120,
      hiringVelocity: "steady_hiring",
      topSkillsInDemand: [
        { skill: "Ruby", count: 85 },
        { skill: "Go", count: 72 },
        { skill: "Distributed Systems", count: 68 },
        { skill: "PostgreSQL", count: 54 },
        { skill: "Kafka", count: 42 },
      ],
      topCategories: [
        { category: "Infrastructure & Systems", count: 120 },
        { category: "Backend Engineering", count: 95 },
        { category: "Product Engineering", count: 65 },
        { category: "Security", count: 32 },
      ],
      geographicFootprint: {
        primaryHubs: [
          { location: "San Francisco, CA", count: 140 },
          { location: "Seattle, WA", count: 65 },
          { location: "Dublin, Ireland", count: 55 },
          { location: "Remote (US)", count: 82 },
        ],
        totalDistinctLocations: 6,
        remoteFriendlyScore: 78,
      },
    },
    distributions: {
      seniority: {
        entry: { count: 12, percentage: 4 },
        mid: { count: 85, percentage: 25 },
        senior: { count: 154, percentage: 45 },
        lead: { count: 58, percentage: 17 },
        principal: { count: 33, percentage: 9 },
      },
      workplace: {
        remote: { count: 120, percentage: 35 },
        hybrid: { count: 190, percentage: 55 },
        onsite: { count: 32, percentage: 10 },
      },
    },
    compensation: {
      transparencyRate: 98,
      observedMinSalary: 165000,
      observedMaxSalary: 385000,
      observedMedianSalary: 245000,
      currency: "USD",
      grade: "VERY_HIGH",
    },
    hiringReport: {
      companyId: "comp-stripe",
      velocityTrend: {
        accelerationStatus: "STABLE",
        growthRatePct: 12.5,
        trendDirection: "EXPANDING",
        volatilityScore: 18,
      },
      windows: {
        window7d: {
          windowDays: 7,
          postingsCount: 12,
          postingsPerWeek: 12,
          activeRatio: 98,
          departmentsBreakdown: [],
          seniorityBreakdown: {
            entry: { count: 1, percentage: 8 },
            mid: { count: 3, percentage: 25 },
            senior: { count: 6, percentage: 50 },
            lead: { count: 2, percentage: 17 },
            principal: { count: 0, percentage: 0 },
            executive: { count: 0, percentage: 0 },
            unknown: { count: 0, percentage: 0 },
          },
          workplaceBreakdown: {
            remote: { count: 4, percentage: 33 },
            hybrid: { count: 7, percentage: 58 },
            onsite: { count: 1, percentage: 9 },
            unknown: { count: 0, percentage: 0 },
          },
        },
        window30d: {
          windowDays: 30,
          postingsCount: 48,
          postingsPerWeek: 12,
          activeRatio: 96,
          departmentsBreakdown: [],
          seniorityBreakdown: {
            entry: { count: 2, percentage: 4 },
            mid: { count: 12, percentage: 25 },
            senior: { count: 22, percentage: 46 },
            lead: { count: 8, percentage: 17 },
            principal: { count: 4, percentage: 8 },
            executive: { count: 0, percentage: 0 },
            unknown: { count: 0, percentage: 0 },
          },
          workplaceBreakdown: {
            remote: { count: 17, percentage: 35 },
            hybrid: { count: 26, percentage: 55 },
            onsite: { count: 5, percentage: 10 },
            unknown: { count: 0, percentage: 0 },
          },
        },
        window90d: {
          windowDays: 90,
          postingsCount: 120,
          postingsPerWeek: 10,
          activeRatio: 92,
          departmentsBreakdown: [],
          seniorityBreakdown: {
            entry: { count: 5, percentage: 4 },
            mid: { count: 30, percentage: 25 },
            senior: { count: 54, percentage: 45 },
            lead: { count: 20, percentage: 17 },
            principal: { count: 11, percentage: 9 },
            executive: { count: 0, percentage: 0 },
            unknown: { count: 0, percentage: 0 },
          },
          workplaceBreakdown: {
            remote: { count: 42, percentage: 35 },
            hybrid: { count: 66, percentage: 55 },
            onsite: { count: 12, percentage: 10 },
            unknown: { count: 0, percentage: 0 },
          },
        },
      },
      composition: {
        concentration: {
          concentrationScore: 42,
          primaryGrowthDepartment: "Infrastructure",
          departmentDiversityGrade: "WELL_DIVERSIFIED",
        },
        roleEvolution: {
          leadershipHiringRatio: 71,
          earlyCareerIntakeRatio: 4,
          newRoleFamiliesCount: 3,
          topEmergingSkills: [],
        },
        workplaceEvolution: {
          remoteIntakeRatio30d: 35,
          remoteIntakeRatio90d: 35,
          remoteTrendDirection: "STABLE",
          newLocationsCount30d: 0,
          emergingLocations: [],
        },
        persistence: {
          averageJobAgeDays: 24,
          persistentOpeningsCount: 8,
          rapidTurnoverCount: 14,
          persistenceTier: "BALANCED",
        },
      },
      primaryHiringDrivers: ["FINANCIAL_INFRASTRUCTURE", "GLOBAL_EXPANSION"],
      evidence: "FACT",
      calculatedAt: new Date(),
    },
  },
  {
    identity: {
      id: "comp-cloudflare",
      name: "Cloudflare",
      slug: "cloudflare",
      logoUrl: null,
      websiteUrl: "https://cloudflare.com",
    },
    profile: {
      domain: "cloudflare.com",
      industry: "Cloud Infrastructure & Cybersecurity",
      headquarters: "San Francisco, CA",
      employeeCount: 3500,
      description: "Cloudflare is on a mission to help build a better Internet. We protect and accelerate any Internet application online without adding hardware, installing software, or changing a line of code.",
      techStack: ["Rust", "Go", "C++", "V8", "PostgreSQL", "ClickHouse", "Kubernetes", "Linux Kernel"],
    },
    hiring: {
      activeJobCount: 180,
      newJobsLast30Days: 24,
      newJobsLast90Days: 68,
      hiringVelocity: "steady_hiring",
      topSkillsInDemand: [
        { skill: "Rust", count: 45 },
        { skill: "Go", count: 38 },
        { skill: "Distributed Systems", count: 35 },
        { skill: "Linux Kernel", count: 28 },
        { skill: "C++", count: 22 },
      ],
      topCategories: [
        { category: "Infrastructure & Systems", count: 85 },
        { category: "Security & Cloud", count: 45 },
        { category: "Product Engineering", count: 30 },
        { category: "Developer Relations", count: 20 },
      ],
      geographicFootprint: {
        primaryHubs: [
          { location: "Austin, TX", count: 65 },
          { location: "San Francisco, CA", count: 55 },
          { location: "London, UK", count: 35 },
          { location: "Remote (Global)", count: 25 },
        ],
        totalDistinctLocations: 4,
        remoteFriendlyScore: 82,
      },
    },
    distributions: {
      seniority: {
        entry: { count: 8, percentage: 4 },
        mid: { count: 42, percentage: 23 },
        senior: { count: 85, percentage: 47 },
        lead: { count: 30, percentage: 17 },
        principal: { count: 15, percentage: 9 },
      },
      workplace: {
        remote: { count: 80, percentage: 44 },
        hybrid: { count: 80, percentage: 44 },
        onsite: { count: 20, percentage: 12 },
      },
    },
    compensation: {
      transparencyRate: 95,
      observedMinSalary: 160000,
      observedMaxSalary: 340000,
      observedMedianSalary: 235000,
      currency: "USD",
      grade: "HIGH",
    },
    hiringReport: {
      companyId: "comp-cloudflare",
      velocityTrend: {
        accelerationStatus: "STABLE",
        growthRatePct: 8.2,
        trendDirection: "EXPANDING",
        volatilityScore: 12,
      },
      windows: {
        window7d: {
          windowDays: 7,
          postingsCount: 6,
          postingsPerWeek: 6,
          activeRatio: 96,
          departmentsBreakdown: [],
          seniorityBreakdown: {
            entry: { count: 0, percentage: 0 },
            mid: { count: 2, percentage: 33 },
            senior: { count: 3, percentage: 50 },
            lead: { count: 1, percentage: 17 },
            principal: { count: 0, percentage: 0 },
            executive: { count: 0, percentage: 0 },
            unknown: { count: 0, percentage: 0 },
          },
          workplaceBreakdown: {
            remote: { count: 3, percentage: 50 },
            hybrid: { count: 3, percentage: 50 },
            onsite: { count: 0, percentage: 0 },
            unknown: { count: 0, percentage: 0 },
          },
        },
        window30d: {
          windowDays: 30,
          postingsCount: 18,
          postingsPerWeek: 4.5,
          activeRatio: 94,
          departmentsBreakdown: [],
          seniorityBreakdown: {
            entry: { count: 1, percentage: 6 },
            mid: { count: 5, percentage: 28 },
            senior: { count: 8, percentage: 44 },
            lead: { count: 3, percentage: 17 },
            principal: { count: 1, percentage: 5 },
            executive: { count: 0, percentage: 0 },
            unknown: { count: 0, percentage: 0 },
          },
          workplaceBreakdown: {
            remote: { count: 8, percentage: 44 },
            hybrid: { count: 8, percentage: 44 },
            onsite: { count: 2, percentage: 12 },
            unknown: { count: 0, percentage: 0 },
          },
        },
        window90d: {
          windowDays: 90,
          postingsCount: 45,
          postingsPerWeek: 3.5,
          activeRatio: 89,
          departmentsBreakdown: [],
          seniorityBreakdown: {
            entry: { count: 3, percentage: 7 },
            mid: { count: 13, percentage: 29 },
            senior: { count: 20, percentage: 44 },
            lead: { count: 6, percentage: 13 },
            principal: { count: 3, percentage: 7 },
            executive: { count: 0, percentage: 0 },
            unknown: { count: 0, percentage: 0 },
          },
          workplaceBreakdown: {
            remote: { count: 20, percentage: 44 },
            hybrid: { count: 20, percentage: 44 },
            onsite: { count: 5, percentage: 12 },
            unknown: { count: 0, percentage: 0 },
          },
        },
      },
      composition: {
        concentration: {
          concentrationScore: 50,
          primaryGrowthDepartment: "Systems",
          departmentDiversityGrade: "MODERATELY_DIVERSIFIED",
        },
        roleEvolution: {
          leadershipHiringRatio: 66,
          earlyCareerIntakeRatio: 6,
          newRoleFamiliesCount: 1,
          topEmergingSkills: [],
        },
        workplaceEvolution: {
          remoteIntakeRatio30d: 44,
          remoteIntakeRatio90d: 44,
          remoteTrendDirection: "STABLE",
          newLocationsCount30d: 0,
          emergingLocations: [],
        },
        persistence: {
          averageJobAgeDays: 32,
          persistentOpeningsCount: 4,
          rapidTurnoverCount: 5,
          persistenceTier: "BALANCED",
        },
      },
      primaryHiringDrivers: ["EDGE_COMPUTE", "SECURITY"],
      evidence: "FACT",
      calculatedAt: new Date(),
    },
  },
];
